import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import { Search, Calculator, Workflow, Hammer, Landmark, ArrowRight } from "lucide-react";
import { Link } from "wouter";

const steps=[
  ['01','Define the objective','We start with what the investor is trying to accomplish, available resources, timeline, involvement level, and risk tolerance.'],
  ['02','Discover opportunities','HUNTER supports acquisition discovery and investigation so OCG can focus attention on opportunities worth deeper review.'],
  ['03','Underwrite the property','VICTOR supports deeper analysis: comps, ARV, rehab, MAO, financing scenarios, risk, and evidence quality.'],
  ['04','Structure the acquisition','OCG evaluates the appropriate strategy and financing path. For flips, lender capital is explored first when appropriate; DSCR and hold strategies may require liquidity differently.'],
  ['05','Transform strategically','Renovation scope, design direction, materials, budget, target buyer/renter, and exit strategy are treated as one connected investment decision.'],
  ['06','Execute + continue','PIPER supports the acquisition pipeline while OCG manages relationships, negotiations, coordination, and next actions. The goal is not merely one closing — it is better investing capability over time.'],
];

export default function HowItWorks(){return <div className="min-h-screen bg-[#090b0f] text-white"><Navbar/><main className="pt-20"><section className="container py-24 md:py-32"><div className="max-w-4xl"><div className="section-eyebrow mb-5">How OCG works</div><h1 className="text-5xl md:text-8xl font-semibold tracking-[-0.055em] leading-[0.92]">Property → evidence → possibility → numbers → capital → decision.</h1><p className="mt-7 text-xl leading-relaxed text-white/55 max-w-3xl">The technology compresses and organizes work. The investment decision remains grounded in evidence, professional verification where required, and human judgment.</p></div></section><section className="border-y border-white/8 bg-[#0c1017] py-24"><div className="container grid gap-4">{steps.map(([n,t,b])=><div key={n} className="grid md:grid-cols-[90px_0.7fr_1.3fr] gap-5 items-start rounded-2xl border border-white/8 bg-white/[0.025] p-6 md:p-8"><div className="ocg-step-number">{n}</div><h2 className="text-2xl md:text-3xl font-semibold">{t}</h2><p className="text-sm md:text-base leading-relaxed text-white/52">{b}</p></div>)}</div></section><section className="py-24"><div className="container grid lg:grid-cols-4 gap-4">{[[Search,'HUNTER','Finds'],[Calculator,'VICTOR','Analyzes'],[Workflow,'PIPER','Manages'],[Hammer,'OCG','Executes']].map(([Icon,name,verb]:any)=><div className="tech-card" key={name}><Icon size={21} className="text-blue-300"/><div className="mt-7 text-2xl font-bold">{name}</div><div className="mt-2 text-xs uppercase tracking-[0.13em] text-white/35">{verb}</div></div>)}</div></section><section className="bg-white text-[#0b0d12] py-24"><div className="container grid lg:grid-cols-2 gap-14"><div><div className="section-eyebrow !text-blue-700 mb-4">Capital discipline</div><h2 className="text-4xl md:text-6xl font-semibold tracking-[-0.04em]">Having money does not automatically mean spending it.</h2></div><div><p className="text-lg leading-relaxed text-black/55">On fix-and-flip opportunities, OCG generally explores lender capital for acquisition and renovation when appropriate. Client liquidity can be strategically valuable as reserves and financial strength. Other strategies, especially DSCR and longer-term holds, can require direct capital differently. Exact requirements always depend on the property, borrower, lender, and current program terms.</p><Link href="/contact" className="inline-flex mt-8 items-center gap-2 text-sm font-semibold text-blue-700">Discuss your situation <ArrowRight size={15}/></Link></div></div></section></main><Footer/></div>}
