import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import { ArrowRight } from "lucide-react";
import { Link } from "wouter";

const paths = [
  { title:'Fix + Flip', subtitle:'Build capital. Learn execution. Reinvest.', body:'For some investors, a disciplined renovation-and-resale project is the right way to get their feet wet, gain experience, and build additional investable capital. OCG generally explores lender-funded acquisition and renovation first when the borrower and deal support it rather than automatically consuming the client’s liquidity.' },
  { title:'BRRRR', subtitle:'Acquire. Improve. Rent. Refinance. Repeat.', body:'A potential portfolio-growth path when acquisition basis, rehab, rent, refinance assumptions, reserves, and lender requirements align. The refinance is a future event, not a guarantee, so the full structure has to be stress-tested.' },
  { title:'Buy + Hold', subtitle:'Own durable assets with a clear operating plan.', body:'For investors prioritizing long-term ownership, cash flow, appreciation potential, and equity creation. Financing and reserve needs can differ materially from a flip and may place greater demands on available capital.' },
  { title:'Creative Structures', subtitle:'Use structure to solve the right problem.', body:'Seller financing, private capital, bridge structures, partnerships, and other legitimate approaches may create flexibility when appropriate. G can educate and model possibilities, but final structures require property, borrower, lender, and professional review.' },
];

export default function Services(){return <div className="min-h-screen bg-[#090b0f] text-white"><Navbar/><main className="pt-20"><section className="container py-24 md:py-32"><div className="max-w-4xl"><div className="section-eyebrow mb-5">Investment strategies</div><h1 className="text-5xl md:text-8xl font-semibold tracking-[-0.055em] leading-[0.92]">The strategy should fit the investor — not the other way around.</h1><p className="mt-7 text-xl text-white/55 leading-relaxed max-w-3xl">OCG helps investors understand the tradeoffs between building capital, building cash flow, preserving liquidity, financing renovation, and creating a path toward larger long-term goals.</p></div></section><section className="bg-white text-[#0b0d12] py-24"><div className="container grid lg:grid-cols-2 gap-5">{paths.map((p,i)=><div key={p.title} className="strategy-card"><div className="text-xs tracking-[0.18em] text-blue-700">0{i+1}</div><h2 className="mt-7 text-4xl font-semibold">{p.title}</h2><div className="mt-3 text-xs uppercase tracking-[0.1em] text-black/45">{p.subtitle}</div><p className="mt-6 text-base leading-relaxed text-black/58">{p.body}</p></div>)}</div></section><section className="py-24"><div className="container rounded-[30px] border border-white/10 p-8 md:p-14 bg-white/[0.035]"><h2 className="text-4xl md:text-6xl font-semibold tracking-[-0.04em]">Have capital but not a plan?</h2><p className="mt-5 max-w-3xl text-lg text-white/52 leading-relaxed">That is not a problem to hide — it is the beginning of the strategy conversation. We can explore what your liquidity, financing profile, experience, timeline, and goals make worth considering before recommending a specific acquisition structure.</p><Link href="/contact" className="btn-gold mt-8">Book Strategy Session <ArrowRight size={15}/></Link></div></section></main><Footer/></div>}
